In [2]:
import numpy as np

In [4]:
a = [[1,2],[3,4],[4,5]]


exp = [[-1,-1,-1]]
c = np.subtract.outer(a,a)
c

array([[[[ 0, -1],
         [-2, -3],
         [-3, -4]],

        [[ 1,  0],
         [-1, -2],
         [-2, -3]]],


       [[[ 2,  1],
         [ 0, -1],
         [-1, -2]],

        [[ 3,  2],
         [ 1,  0],
         [ 0, -1]]],


       [[[ 3,  2],
         [ 1,  0],
         [ 0, -1]],

        [[ 4,  3],
         [ 2,  1],
         [ 1,  0]]]])

In [5]:
a = [1,2]
b = [4,5]
np.outer(a,b)

array([[ 4,  5],
       [ 8, 10]])

In [3]:
a = np.zeros((1,2,3))

In [4]:
a.transpose((2,0,1))

array([[[0., 0.]],

       [[0., 0.]],

       [[0., 0.]]])